Repository EA31337/EA31337-classes, pull requests merged in 2019-11, with the labels that each got.

#86 Changed .travis.yml VM distro to trusty
  .travis.yml
Labels: bug

#87 Fixes broken CI build
  .travis.yml
  tests/docker-compose.yml
Labels: bug

#80 Adds MarketTest
  .travis.yml
  Market.mqh
  README.md
  SymbolInfo.mqh
  tests/MarketTest.mq4
  tests/MarketTest.mq5
  tests/SymbolInfoTest.mq4
  tests/SymbolInfoTest.mq5
  tests/docker-compose.yml
Labels: enhancement

#75 Adds AccountTest
  .travis.yml
  Account.mqh
  README.md
  tests/AccountTest.mq4
  tests/AccountTest.mq5
  tests/docker-compose.yml
Labels: bug, enhancement

#78 Adds conversion for predefined variables
  README.md
Labels: enhancement

#72 Removes Check class
  Check.mqh
Labels: enhancement

#77 Removes OHLC methods from Market
  Chart.mqh
  Condition.mqh
  Market.mqh
  tests/StrategyTest.mq5
  tests/TradeTest.mq5
Labels: enhancement
