Repository EA31337/EA31337-classes, pull requests merged in 2020-12, with the labels that each got.

#380 CSV Serializer fixes and improvements
  Indicator.struct.h
  Indicators/Indi_RSI.mqh
  Matrix.mqh
  Serializer.mqh
  SerializerConverter.mqh
  SerializerCsv.mqh
  SerializerJson.mqh
  Strategy.struct.h
  tests/MatrixTest.mq5
  tests/SerializerTest.mq5
Labels: bug, enhancement

#381 CSV Serializer fixes and improvements
  Indicator.struct.h
  Indicators/Indi_RSI.mqh
  Serializer.mqh
  SerializerConverter.mqh
  SerializerCsv.mqh
  SerializerJson.mqh
  Strategy.struct.h
  tests/SerializerTest.mq5
Labels: bug, enhancement

#384 Development improvements
  BufferStruct.mqh
  Chart.mqh
  Chart.struct.h
  Convert.mqh
  Draw.mqh
  DrawIndicator.mqh
  Indicator.enum.h
  Indicator.mqh
  Indicator.struct.h
  MQL4.mqh
  Market.mqh
  Order.mqh
  Terminal.mqh
  tests/BufferStructTest.mq5
  tests/SerializerTest.mq5
Labels: enhancement

#385 Order fixes and improvements
  Account.mqh
  Chart.mqh
  EA.mqh
  Market.mqh
  Order.mqh
Labels: bug, enhancement

#386 EA: Adds support for data export
  Convert.mqh
  DictStruct.mqh
  EA.mqh
  Indicator.struct.h
  Strategy.struct.h
  SymbolInfo.mqh
Labels: enhancement

#388 Indicator data refactor with export and serialization fixes
  Config.mqh
  DictObject.mqh
  DictStruct.mqh
  EA.mqh
  Indicator.enum.h
  Indicator.mqh
  Indicator.struct.h
  Indicators/Indi_AC.mqh
  Indicators/Indi_AD.mqh
  Indicators/Indi_ADX.mqh
  Indicators/Indi_AO.mqh
  Indicators/Indi_ATR.mqh
  Indicators/Indi_Alligator.mqh
  Indicators/Indi_BWMFI.mqh
  Indicators/Indi_Bands.mqh
  Indicators/Indi_BearsPower.mqh
  Indicators/Indi_BullsPower.mqh
  Indicators/Indi_CCI.mqh
  Indicators/Indi_DeMarker.mqh
  Indicators/Indi_Demo.mqh
  Indicators/Indi_Envelopes.mqh
  Indicators/Indi_Force.mqh
  Indicators/Indi_Fractals.mqh
  Indicators/Indi_Gator.mqh
  Indicators/Indi_HeikenAshi.mqh
  Indicators/Indi_Ichimoku.mqh
  Indicators/Indi_MA.mqh
  Indicators/Indi_MACD.mqh
  Indicators/Indi_MFI.mqh
  Indicators/Indi_Momentum.mqh
  Indicators/Indi_OBV.mqh
  Indicators/Indi_OsMA.mqh
  Indicators/Indi_Price.mqh
  Indicators/Indi_PriceFeeder.mqh
  Indicators/Indi_RSI.mqh
  Indicators/Indi_RVI.mqh
  Indicators/Indi_SAR.mqh
  Indicators/Indi_StdDev.mqh
  Indicators/Indi_Stochastic.mqh
  Indicators/Indi_WPR.mqh
  Indicators/Indi_ZigZag.mqh
  Math.h
  Math.struct.h
  Serializer.mqh
  SerializerConverter.mqh
  SerializerCsv.mqh
  SerializerNode.mqh
  tests/ConfigTest.mq5
  tests/IndicatorsTest.mq5
  tests/SerializerTest.mq5
Labels: enhancement

#391 CSV Serializer and Serializer features
  Serializer.mqh
  SerializerCsv.mqh
  SerializerNode.enum.h
  SerializerNode.mqh
  SerializerNodeParam.mqh
  tests/SerializerTest.mq5
Labels: enhancement

#392 Adds BarEntry and support for candle patterns
  .github/workflows/compile.yml
  Bar.enum.h
  Bar.struct.h
  Chart.enum.h
  Chart.mqh
  Chart.struct.h
  EA.mqh
  Indicator.struct.h
  Indicators/Indi_CCI.mqh
  Indicators/Indi_Envelopes.mqh
  Indicators/Indi_Momentum.mqh
  Strategy.mqh
Labels: enhancement

#393 Indi_Drawer indicator [WIP]
  Account.mqh
  Action.mqh
  Action.struct.h
  Chart.mqh
  Condition.struct.h
  DateTime.mqh
  Dict.mqh
  DrawIndicator.mqh
  EA.mqh
  Indicator.enum.h
  Indicator.mqh
  Indicator.struct.h
  Indicators/Indi_Drawer.mqh
  Market.mqh
  Math.h
  Order.mqh
  Order.struct.h
  Redis.mqh
  Serializer.mqh
  SerializerNodeParam.mqh
  Socket.mqh
  Strategy.mqh
  Task.mqh
  Trade.mqh
  tests/IndicatorsTest.mq5
Labels: enhancement

#394 Trade: Fixes IsTradeAllowed() for backtesting (fixes GH-368)
  Trade.mqh
Labels: bug

#395 Development improvements
  .github/workflows/test.yml
  Bar.enum.h
  Bar.struct.h
  BufferStruct.mqh
  Chart.struct.h
  Convert.mqh
  Dict.mqh
  EA.mqh
  Indicator.struct.h
  Math.h
  Matrix.mqh
  SerializerConverter.mqh
  tests/MathTest.mq4
  tests/MathTest.mq5
Labels: enhancement
