Repository EA31337/EA31337-classes, pull requests merged in 2020-11, with the labels that each got.

#351 TaskEntry refactor and initial DataExport()
  Action.enum.h
  Action.mqh
  Action.struct.h
  Chart.mqh
  Chart.struct.h
  Condition.enum.h
  Condition.mqh
  Condition.struct.h
  EA.enum.h
  EA.mqh
  EA.struct.h
  JsonNode.enum.h
  JsonNode.mqh
  JsonSerializer.enum.h
  JsonSerializer.mqh
  Strategy.mqh
  Strategy.struct.h
  Task.mqh
  Task.struct.h
Labels: enhancement

#353 Matrix fixes
  .github/workflows/compile.yml
  .github/workflows/test.yml
  Math.mqh
  Matrix.mqh
  tests/MatrixTest.mq5
Labels: enhancement

#354 Order: Fixes order processing and close condition
  .github/workflows/lint.yml
  Action.enum.h
  Action.mqh
  Action.struct.h
  Condition.enum.h
  Condition.mqh
  EA.mqh
  Order.enum.h
  Order.mqh
  Order.struct.h
  Strategy.mqh
  Strategy.struct.h
  Task.struct.h
Labels: enhancement

#355 Order refactor
  Order.mqh
  Order.struct.h
  Orders.mqh
Labels: enhancement

#358 Development improvements
  Chart.mqh
  Chart.struct.h
  Condition.enum.h
  Condition.mqh
  Convert.mqh
  EA.mqh
  Indicator.enum.h
  Indicator.mqh
  Indicator.struct.h
  Market.mqh
  Math.enum.h
  Math.h
  Math.struct.h
  Matrix.mqh
  Orders.mqh
  Strategy.mqh
  Timer.mqh
  Trade.mqh
Labels: enhancement

#360 Strategy signal refactor and fixes
  Condition.enum.h
  Indicator.mqh
  Indicators/Indi_RSI.mqh
  Matrix.mqh
  Strategy.enum.h
  Strategy.mqh
  Strategy.struct.h
Labels: enhancement

#361 Serializer refactor with new SerializerCSV SerializerJson classes
  BufferStruct.mqh
  Chart.mqh
  Chart.struct.h
  Config.mqh
  Dict.mqh
  DictBase.mqh
  DictIteratorBase.mqh
  DictObject.mqh
  DictRef.mqh
  DictStruct.mqh
  EA.mqh
  File.mqh
  Indicators/Indi_RSI.mqh
  JsonParam.mqh
  JsonSerializer.mqh
  Matrix.mqh
  Redis.mqh
  Serializer.enum.h
  Serializer.mqh
  SerializerConverter.mqh
  SerializerCsv.mqh
  SerializerJson.mqh
  SerializerNode.enum.h
  SerializerNode.mqh
  SerializerNodeIterator.mqh
  SerializerNodeParam.mqh
  SerializerObject.mqh
  tests/BufferStructTest.mq5
  tests/ConfigTest.mq5
  tests/DictTest.mq5
  tests/SerializerTest.mq4
  tests/SerializerTest.mq5
  tests/docker-compose.yml
Labels: enhancement

#362 Fixes Dict bug, stack overflow and dynamic-based object destruction
  Dict.mqh
  DictObject.mqh
  DictRef.mqh
  DictStruct.mqh
  EA.mqh
Labels: enhancement

#365 Fixed memory leaks, delete loop and Dict bug in copy constructor.
  Action.mqh
  Condition.mqh
  Dict.mqh
  DictObject.mqh
  DictRef.mqh
  DictStruct.mqh
  Refs.mqh
  Strategy.mqh
  Strategy.struct.h
Labels: enhancement

#364 Dict/EA: Bug fixes and improvements
  Action.mqh
  Condition.mqh
  Dict.mqh
  DictObject.mqh
  DictRef.mqh
  DictStruct.mqh
  EA.mqh
  Refs.mqh
  Strategy.mqh
  Strategy.struct.h
  tests/DictTest.mq5
Labels: bug, enhancement

#366 Fixed MinOf() for double type.
  Matrix.mqh
Labels: bug

#367 Development improvements
  Action.enum.h
  Action.mqh
  Action.struct.h
  BufferStruct.mqh
  Chart.mqh
  Chart.struct.h
  Condition.enum.h
  Condition.mqh
  Condition.struct.h
  Convert.mqh
  Indicator.enum.h
  Indicator.mqh
  Indicator.struct.h
  IndicatorData.mqh
  Indicators/Indi_MA.mqh
  Matrix.mqh
  SerializerNode.enum.h
  Strategy.enum.h
  Strategy.mqh
  Strategy.struct.h
  Task.enum.h
  Task.struct.h
Labels: enhancement

#369 Strategy: API: Renames PriceLimit to PriceStop
  Strategy.mqh
  Strategy.struct.h
  tests/ActionTest.mq5
  tests/StrategyTest.mq5
  tests/TaskTest.mq5
Labels: enhancement

#370 Strategy: Adds TrendStrength()
  Chart.mqh
  Strategy.mqh
  Strategy.struct.h
Labels: enhancement

#371 Development improvements
  Account.enum.h
  Account.mqh
  Account.struct.h
  Action.enum.h
  Action.mqh
  Action.struct.h
  Condition.enum.h
  Condition.mqh
  Condition.struct.h
  DateTime.enum.h
  DateTime.mqh
  DateTime.struct.h
  Session.mqh
  Strategy.enum.h
  Strategy.mqh
  Trade.enum.h
  Trade.mqh
  Trade.struct.h
Labels: enhancement

#372 Added copy constructor to Matrix class.
  Matrix.mqh
  tests/MatrixTest.mq5
Labels: enhancement

#375 Order logic fixes
  Market.mqh
  Order.mqh
  Strategy.mqh
  Trade.mqh
Labels: MQL4, MQL5, bug, enhancement

#378 Adds serializers for ChartParams/IndicatorParams/StgParams
  Chart.struct.h
  Indicator.struct.h
  Indicators/Indi_RSI.mqh
  SerializerNodeParam.mqh
  Strategy.struct.h
Labels: enhancement

#379 Development enhancements
  Indicator.mqh
  Matrix.mqh
  tests/MatrixTest.mq5
Labels: enhancement
