Repository EA31337/EA31337-classes, pull requests merged in 2020-03, with the labels that each got.

#137 BufferStruct class fixes [GH-128]
  BufferStruct.mqh
  Dict.mqh
  DictStruct.mqh
  tests/BufferStructTest.mq5
Labels: enhancement

#136 BufferStruct class [GH-128]; New classes: JsonIterator/JsonNode/JsonParam/JsonSerializer; Config/Dict/DictStruct/JSON improvements
  BufferStruct.mqh
  Config.mqh
  Convert.mqh
  Dict.mqh
  DictBase.mqh
  DictObject.mqh
  DictStruct.mqh
  Indicators/Indi_AC.mqh
  JSON.mqh
  JsonIterator.mqh
  JsonNode.mqh
  JsonParam.mqh
  JsonSerializer.mqh
  tests/BufferStructTest.mq4
  tests/BufferStructTest.mq5
  tests/ConfigTest.mq5
  tests/DictTest.mq5
Labels: enhancement

#140 Fixes #138 (Dict Resize() bug)
  Dict.mqh
  DictBase.mqh
  DictObject.mqh
  DictStruct.mqh
Labels: bug

#141 Added better test to check if Dict values are all added.
  tests/DictTest.mq5
Labels: enhancement

#144 Fixes #143. CHIKOUSPAN value retrieval requires shift to be at least …
  Indicators/Indi_Ichimoku.mqh
Labels: bug

#148 Indicator fixes
  DictBase.mqh
  DictStruct.mqh
  Indicator.mqh
  Indicators/Indi_AC.mqh
  Indicators/Indi_AD.mqh
  Indicators/Indi_ADX.mqh
  Indicators/Indi_AO.mqh
  Indicators/Indi_ATR.mqh
  Indicators/Indi_Alligator.mqh
  Indicators/Indi_BWMFI.mqh
  Indicators/Indi_Bands.mqh
  Indicators/Indi_BearsPower.mqh
  Indicators/Indi_BullsPower.mqh
  Indicators/Indi_CCI.mqh
  Indicators/Indi_DeMarker.mqh
  Indicators/Indi_Envelopes.mqh
  Indicators/Indi_Force.mqh
  Indicators/Indi_Fractals.mqh
  Indicators/Indi_Gator.mqh
  Indicators/Indi_HeikenAshi.mqh
  Indicators/Indi_Ichimoku.mqh
  Indicators/Indi_MA.mqh
  Indicators/Indi_MACD.mqh
  Indicators/Indi_MFI.mqh
  Indicators/Indi_Momentum.mqh
  Indicators/Indi_OBV.mqh
  Indicators/Indi_OsMA.mqh
  Indicators/Indi_RSI.mqh
  Indicators/Indi_RVI.mqh
  Indicators/Indi_SAR.mqh
  Indicators/Indi_StdDev.mqh
  Indicators/Indi_Stochastic.mqh
  Indicators/Indi_WPR.mqh
  Indicators/Indi_ZigZag.mqh
  tests/IndicatorsTest.mq5
Labels: enhancement, on-hold

#151 Indicator improvements
  Indicator.mqh
  Market.mqh
  Order.mqh
  Strategy.mqh
  Trade.mqh
Labels: enhancement

#153 Indi_BWMFI fixes for MT4 [GH-149]
  Indicators/Indi_BWMFI.mqh
  tests/IndicatorsTest.mq5
Labels: bug, enhancement

#154 Order and JSON fixes; Adds OrderTest
  .travis.yml
  Config.mqh
  DictBase.mqh
  JSON.mqh
  JsonParam.mqh
  JsonSerializer.mqh
  Order.mqh
  Orders.mqh
  SymbolInfo.mqh
  tests/ConfigTest.mq5
  tests/DictTest.mq5
  tests/OrderTest.mq4
  tests/OrderTest.mq5
  tests/docker-compose.yml
Labels: bug, enhancement

#172 Making code to compile under MT4
  Condition.mqh
  tests/ConditionTest.mq5
Labels: enhancement
