Repository EA31337/EA31337-classes, pull requests merged in 2020-07, with the labels that each got.

#273 OrderProfit() for MT5 and other fixes
  Object.mqh
  Order.mqh
  Strategy.mqh
Labels: bug

#278 Order fixes for MT5 [GH-272]
  Action.mqh
  Object.mqh
  Order.mqh
  Strategy.mqh
Labels: bug, enhancement

#283 Order::IsOpen() could end up with "Position not found" error
  Order.mqh
Labels: enhancement

#288 Adds initial EA test
  .github/workflows/test.yml
  EA.mqh
  tests/EATest.mq4
  tests/EATest.mq5
  tests/docker-compose.yml
Labels: enhancement

#291 GHA: Runs test in parallel
  .github/workflows/test.yml
  tests/EATest.mq5
Labels: enhancement

#289 API: Renames Process() to ProcessTick(); Adds TickFilter()
  EA.mqh
  Strategy.mqh
Labels: enhancement

#294 Strategy API improvements
  .github/workflows/test.yml
  Strategy.mqh
  Trade.mqh
  tests/ActionTest.mq5
  tests/StrategyTest.mq5
  tests/TaskTest.mq5
Labels: enhancement

#296 OrderSelect() will now clear last error by default
  Order.mqh
Labels: enhancement

#299 Improves MQL4 backward compability
  .github/workflows/compile.yml
  Chart.mqh
  Convert.mqh
  DateTime.mqh
  Draw.mqh
  Indicator.mqh
  Indicators/Indi_AC.mqh
  Indicators/Indi_AD.mqh
  Indicators/Indi_ADX.mqh
  Indicators/Indi_AO.mqh
  Indicators/Indi_ATR.mqh
  Indicators/Indi_Alligator.mqh
  Indicators/Indi_BWMFI.mqh
  Indicators/Indi_Bands.mqh
  Indicators/Indi_BearsPower.mqh
  Indicators/Indi_BullsPower.mqh
  Indicators/Indi_CCI.mqh
  Indicators/Indi_DeMarker.mqh
  Indicators/Indi_Envelopes.mqh
  Indicators/Indi_Force.mqh
  Indicators/Indi_Fractals.mqh
  Indicators/Indi_Gator.mqh
  Indicators/Indi_Ichimoku.mqh
  Indicators/Indi_MA.mqh
  Indicators/Indi_MACD.mqh
  Indicators/Indi_MFI.mqh
  Indicators/Indi_Momentum.mqh
  Indicators/Indi_OBV.mqh
  Indicators/Indi_OsMA.mqh
  Indicators/Indi_RSI.mqh
  Indicators/Indi_RVI.mqh
  Indicators/Indi_SAR.mqh
  Indicators/Indi_StdDev.mqh
  Indicators/Indi_Stochastic.mqh
  Indicators/Indi_WPR.mqh
  Log.mqh
  MQL4.mqh
  Profiler.mqh
  Terminal.mqh
  tests/TerminalTest.mq5
Labels: enhancement

#302 Development fixes for MQL5
  Draw.mqh
  Indicators/Indi_AC.mqh
  Indicators/Indi_AD.mqh
  Indicators/Indi_ADX.mqh
  Indicators/Indi_AO.mqh
  Indicators/Indi_ATR.mqh
  Indicators/Indi_Alligator.mqh
  Indicators/Indi_BWMFI.mqh
  Indicators/Indi_Bands.mqh
  Indicators/Indi_BearsPower.mqh
  Indicators/Indi_BullsPower.mqh
  Indicators/Indi_CCI.mqh
  Indicators/Indi_DeMarker.mqh
  Indicators/Indi_Envelopes.mqh
  Indicators/Indi_Force.mqh
  Indicators/Indi_Fractals.mqh
  Indicators/Indi_Gator.mqh
  Indicators/Indi_HeikenAshi.mqh
  Indicators/Indi_Ichimoku.mqh
  Indicators/Indi_MA.mqh
  Indicators/Indi_MACD.mqh
  Indicators/Indi_MFI.mqh
  Indicators/Indi_Momentum.mqh
  Indicators/Indi_OBV.mqh
  Indicators/Indi_OsMA.mqh
  Indicators/Indi_RSI.mqh
  Indicators/Indi_RVI.mqh
  Indicators/Indi_SAR.mqh
  Indicators/Indi_StdDev.mqh
  Indicators/Indi_Stochastic.mqh
  Indicators/Indi_WPR.mqh
  Indicators/Indi_ZigZag.mqh
Labels: MQL5, enhancement

#297 Strategy improvements
  .github/workflows/test.yml
  Account.mqh
  Market.mqh
  Order.mqh
  Refs.mqh
  Strategy.mqh
  Trade.mqh
  tests/AccountTest.mq5
Labels: enhancement

#306 Cross-platform compatibility fixes
  Chart.mqh
  EA.mqh
  Indicator.mqh
  Indicators/Indi_MA.mqh
Labels: enhancement
