Repository EA31337/EA31337-classes, pull requests merged in 2022-01, with the labels that each got.

#629 Added SerializeStub() method to Chart class. Added more error checks.
  Chart.mqh
  Serializer.mqh
  SerializerConverter.mqh
  SerializerCsv.mqh
  SerializerNode.mqh
Labels: enhancement

#630 Initial new Account classes
  .github/workflows/test-account.yml
  Account.mqh
  Account/Account.define.h
  Account/Account.enum.h
  Account/Account.h
  Account/Account.struct.h
  Account/AccountBase.h
  Account/AccountBase.struct.h
  Account/AccountForex.h
  Account/AccountForex.struct.h
  Account/tests/Account.test.mq4
  Account/tests/Account.test.mq5
  Account/tests/AccountForex.test.mq4
  Account/tests/AccountForex.test.mq5
  Action.struct.h
  Condition.struct.h
  Convert.mqh
Labels: enhancement

#621 Initial Exchange class
  .github/workflows/test-exchange.yml
  Account.mqh
  Exchange/Exchange.h
  Exchange/Exchange.struct.h
  Exchange/tests/Exchange.test.mq4
  Exchange/tests/Exchange.test.mq5
  SymbolInfo.mqh
  SymbolInfo.struct.h
Labels: enhancement

#632 Indicator logic refactor (part 2)
  IndicatorBase.h
  Indicators/Bitwise/Indi_Candle.mqh
  Indicators/Bitwise/Indi_Pattern.mqh
  Indicators/Indi_Pivot.mqh
  Indicators/Special/Indi_Math.mqh
  Storage/ValueStorage.indicator.h
  tests/IndicatorTest.mq5
Labels: enhancement

#635 Fixed DictObjectIterator's value pointer's cast
  Task/Task.h
  Task/Task.struct.h
  Task/TaskManager.h
  Task/tests/TaskManager.test.mq5
Labels: bug

#640 Should fix new issues with C++ compatibility.
  DictObject.mqh
  SerializerConverter.mqh
  Tick.struct.h
Labels: enhancement, C++

#641 Added TaskManager::Add(string _entry) method
  SerializerConverter.mqh
  Task/Task.struct.h
  Task/TaskCondition.struct.h
  Task/TaskManager.h
  Task/tests/TaskManager.test.mq5
Labels: enhancement

#643 Development enhancements
  CONTRIBUTING.md
  EA.mqh
  Order.mqh
  README.md
  Strategy.mqh
  tests/IndicatorsTest.mq5
Labels: enhancement
